// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA0ULgMCeuX9YZMFsEncTYVRK4RwQKBcI',
    appId: '1:582481205646:web:84fcdda88d3de157e4ecdf',
    messagingSenderId: '582481205646',
    projectId: 'final-year-project-perfecto',
    authDomain: 'final-year-project-perfecto.firebaseapp.com',
    storageBucket: 'final-year-project-perfecto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKjIAK82p_hbIghjyGhdYuVqA5VbXxw5Q',
    appId: '1:582481205646:android:cef795a4c86ab028e4ecdf',
    messagingSenderId: '582481205646',
    projectId: 'final-year-project-perfecto',
    storageBucket: 'final-year-project-perfecto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87bo2FthlzGMVBNnKRQbUTeRL7aPvptA',
    appId: '1:582481205646:ios:2759a96250f250d1e4ecdf',
    messagingSenderId: '582481205646',
    projectId: 'final-year-project-perfecto',
    storageBucket: 'final-year-project-perfecto.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC87bo2FthlzGMVBNnKRQbUTeRL7aPvptA',
    appId: '1:582481205646:ios:2759a96250f250d1e4ecdf',
    messagingSenderId: '582481205646',
    projectId: 'final-year-project-perfecto',
    storageBucket: 'final-year-project-perfecto.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA0ULgMCeuX9YZMFsEncTYVRK4RwQKBcI',
    appId: '1:582481205646:web:47d173d527072024e4ecdf',
    messagingSenderId: '582481205646',
    projectId: 'final-year-project-perfecto',
    authDomain: 'final-year-project-perfecto.firebaseapp.com',
    storageBucket: 'final-year-project-perfecto.firebasestorage.app',
  );
}
